### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by FredrikAugust** [Tijndagamer/db_manager_project#1]
I'm very sorry to announce this, but what you have created here is not a Database Management System, and it is not creating databases either. 

I'm just going to leave this here, putting emphasis on the word _organized_:

"A database is an organized collection of data. The data is typically organized to model aspects of reality in a way that supports processes requiring information. For example, modelling the availability of rooms in hotels in a way that supports finding a hotel with vacancies."

That is the definition of a database, compare this to what you have created, and you will find there are few similarities. Now. What you are trying to create is a Database Management System. 

Taken from the same wiki page as the previous quote:

"Database management systems are computer software applications that interact with the user, other applications, and the database itself to capture and analyze data. A general-purpose DBMS is designed to allow the definition, creation, querying, update, and administration of databases."

Once again, compare the two and you will find few similarities. 

If you are planning on rewriting this script, I would recommend you using a lib such as "peewee" or similar. As this is used for making actual Databases, and interacting with them. Because as of right now, this is offensive, and nearly a threat to all sysadmins and similar. Me, myself, and even I are all sitting here facepalming over this horrible ___thing___.

If I managed to get you to rewrite this text, feel emotional, or stop procrastinating on reddit please consider this issue done. Thank you for your time.

**Comment by Tijndagamer** [comment]
This is just some old project, just roll with it
